### ISSUE TITLE
nasa-public-domain demo link is broken

### ISSUE THREAD

**Issue by DefteZ** [ip-tools/ip-navigator#17]
demo "The nasa-public-domain demo displays the latest NASA patents put under the public domain" in README  is broken ([url](https://patentview.ip-tools.io/?op=eyJhbGciOiAiUlMyNTYiLCAidHlwIjogIkpXVCJ9.eyJqdGkiOiAieWJtZDRWeEtlcDlvcW1YaFM0a2NwQT09IiwgImRhdGEiOiB7InByb2plY3QiOiAibmFzYS1wdWJsaWMtZG9tYWluLXJlY2VudCIsICJkYXRhc291cmNlIjogInJldmlldyIsICJjb250ZXh0IjogInZpZXdlciIsICJ0dGwiOiAiMTU2MzQ4MDAiLCAibW9kZSI6ICJsaXZldmlldyIsICJudW1iZXJsaXN0IjogIlVTNTY4OTAwNCxVUzcwMDg2MDUsVVM3MDIzMTE4LFVTNzQzODAzMCxVUzc3NzMzNjIsVVM3NzkwMTI4LFVTNzgwODM1MyxVUzc5MDA0MzYsVVM3OTMzMDI3LFVTODIxMjEzOCxVUzgyNTkxMDQsVVM4NDA3OTc5LFVTODc2MzM2MixVUzg5Mzg5NzQsVVM5MDE2NjMyLFVTOTAyMTc4MixVUzkwOTE0OTAsVVM5MTk0MzM0In0sICJuYmYiOiAxNTA5NDI4NjI2LCAiZXhwIjogMTUyNTA2MzQyNiwgImlhdCI6IDE1MDk0Mjg2MjZ9.hFx5wWhi-n4w8ZJTVGC7liQeMfqpH8VTpRfmT6twfM4As23MBTwlsmg0u2frfYs0zV6qCsQngwwvQ2Tn6VCju8yf5GBIG5erB3VFyOr_EtZejFJOqTO6A5esEcUtyeXZ))

Reason: has expired at 2018-04-30 06:43:46 ("exp": 1525063426 from JWT)

**Comment by amotl** [comment]
Dear Andrii,

thanks for spotting this. Actually, we have been aware of it, but you made us finally update the link (with one of the next commits).

Cheers,
Andreas.
