### ISSUE TITLE
Data lost

### ISSUE THREAD

**Issue by papoteur-mga** [ip-tools/ip-navigator#28]
Hello,
I have done a search last friday, but today I don't find my file.
In Patzilla navigator, I created a project, then performed my searches and selected some documents.
They was listed in collection of documents area.
Today, I restart the computer and the server, but the interface is virgin like the first day. In projects collection, I have only "ad-hoc" project with 0 documents.
The service mongod is running.
I just installed genghisapp to browse the content of mongodb, I found the database patzilla_development but there is no collection in it.
I run patzilla as user with the sequence :
```
source .venv27/bin/activate
pserve patzilla.ini
```
Are my data saved? Where? How can they be restored?
I'm running Mageia 7 with mongodb-4.1.4

**Comment by amotl** [comment]
Dear @papoteur-mga,

thanks for using PatZilla.

> Are my data saved? Where?

All of the personal data is stored within your Browser, it uses LocalStorage for that. MongoDB is currently just used for the user authentication database.

While we have been planning to move the personal data storage into MongoDB or PostgreSQL, we haven't been able to catch some time and resources to implement this.

With kind regards,
Andreas.

**Comment by papoteur-mga** [comment]
Thanks Andreas for your quick reply.
This is something I didn't figured out, for now.

**Comment by amotl** [comment]
You are welcome. You might want to take care your browser does not delete all LocalStorage content on shutdown.

On the "better safe than sorry" side, you might want to export your database through the user interface regularly or at least when finishing your research session. This way, you can import the database again even when the browser drops all data stored locally.

**Comment by amotl** [comment]
Dear @papoteur-mga,

I hope your question has been answered well, so I am closing this. Please reopen if you need further guidance.

With kind regards,
Andreas.
