### ISSUE TITLE
PatZilla croaks with “HTTPBadGateway: Could not connect to OPS servers”

### ISSUE THREAD

**Issue by amotl** [ip-tools/ip-navigator#9]
After installing PatZilla in development mode on a fresh Ubuntu 18.10 box, customers are reporting a problem to us. While PatZilla starts fine and is apparently properly configured, it bails out when actually accessing the OPS services with this exception:
```
  File "/home/develop/patselect-dev/ip-navigator/patzilla/access/epo/ops/client.py", line 192, in request
    raise error
HTTPBadGateway: Could not connect to OPS servers.
```

**Comment by amotl** [comment]
In the meanwhile, you might want to use the `epo-ops-client` branch if you're in a hurry. We are already working on the next release which will remedy this problem. Please bear with us.

**Comment by amotl** [comment]
## Solution
PatZilla version 0.162.0 resolves the problem with OPS connectivity, as confirmed by @ElvezPelvez and others. Thanks and enjoy your research.

## Background
As @aghster asked over there at #8:
> The issue explained [here] seems to be related to a python update (@amotl, did I get this right?)

Actually, we don't know for sure. But as the switchover from a custom OPS client implementation to George Song's great [python-epo-ops-client](https://github.com/55minutes/python-epo-ops-client) library was long overdue, we just took the chance to finally implement it. Thanks, @gsong!

**Comment by ElvezPelvez** [comment]
Great and thanks a lot!

Btw. where can I leave feature requests? I'd really love to have a function to bulk download selected documents (if possible even specific regarding their kind code)...

**Comment by amotl** [comment]
Dear @ElvezPelvez,

appreciate it, we will be happy to hear about feature requests. Because we found [Discourse](https://discourse.org/) very suitable for managing such things, we would like to invite you over at meta https://meta.ip-tools.org/ and encourage you to drop your suggestions into the [PatZilla development category](https://meta.ip-tools.org/c/patzilla/development).

With kind regards,
Andreas.
